require_relative "../lib/parser/parser.rb"
require_relative "../lib/utils.rb"

describe "lexer" do
    def parse relative_path, show_tokens = false
        absolute_path = __dir__ + "/data/quiet/#{relative_path}"
        content = read_file absolute_path
        Parser.new.parse content, show_tokens
    end
    it "lexer/l05.c" do
        expect(parse("lexer/l05.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[#<struct VariableDeclarationNode type=:INT, name=\"i\">], statments=[#<struct NotEqualNode left=#<struct ConstantNode type=:INT, value=1>, right=#<struct Not expr=#<struct ConstantNode type=:INT, value=3>>>, #<struct AndNode left=#<struct ConstantNode type=:INT, value=4>, right=#<struct ConstantNode type=:INT, value=6>>, #<struct AddNode left=#<struct MulNode left=#<struct ConstantNode type=:INT, value=7>, right=#<struct ConstantNode type=:INT, value=8>>, right=#<struct ConstantNode type=:INT, value=10>>, #<struct AddNode left=#<struct SubNode left=#<struct ConstantNode type=:INT, value=11>, right=#<struct ConstantNode type=:INT, value=12>>, right=#<struct DivNode left=#<struct ConstantNode type=:INT, value=12>, right=#<struct ConstantNode type=:INT, value=16>>>, #<struct LessThanNode left=#<struct LessEqualNode left=#<struct ConstantNode type=:INT, value=17>, right=#<struct ConstantNode type=:INT, value=18>>, right=#<struct UnaryMinus expr=#<struct ConstantNode type=:INT, value=20>>>, #<struct AssignNode left=#<struct IdentifierNode name=\"i\">, right=#<struct EqualNode left=#<struct ConstantNode type=:INT, value=21>, right=#<struct ConstantNode type=:INT, value=22>>>, #<struct GreaterThanNode left=#<struct GreaterEqualNode left=#<struct ConstantNode type=:INT, value=25>, right=#<struct ConstantNode type=:INT, value=27>>, right=#<struct ConstantNode type=:INT, value=28>>]>>]>"
    end
    it "parser/p01.c" do
        expect(parse("parser/p01.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[#<struct VariableDeclarationNode type=:INT, name=\"x\">, #<struct VariableDeclarationNode type=:INT, name=\"y\">], statments=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=42>>, #<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct AssignNode left=#<struct IdentifierNode name=\"y\">, right=#<struct ConstantNode type=:INT, value=4711>>>]>>]>"
    end
    it "parser/p02.c" do
        expect(parse("parser/p02.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[#<struct VariableDeclarationNode type=:INT, name=\"x\">], statments=[#<struct WhileNode condition=#<struct LessThanNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=10>>, body=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct AddNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=3>>>]>, #<struct IfNode condition=#<struct ConstantNode type=:INT, value=1>, then_block=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct AddNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=3>>>], else_block=nil>]>>]>"

    end
    it "parser/p03.c" do
        expect(parse("parser/p03.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[#<struct VariableDeclarationNode type=:INT, name=\"x\">], statments=[#<struct IfNode condition=#<struct LessThanNode left=#<struct ConstantNode type=:INT, value=1>, right=#<struct ConstantNode type=:INT, value=2>>, then_block=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=1>>], else_block=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=2>>]>]>>]>"

    end
    it "parser/p04.c" do
        expect(parse("parser/p04.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[#<struct VariableDeclarationNode type=:INT, name=\"x\">, #<struct VariableDeclarationNode type=:INT, name=\"y\">, #<struct VariableDeclarationNode type=:INT, name=\"z\">], statments=[#<struct SubNode left=#<struct SubNode left=#<struct SubNode left=#<struct IdentifierNode name=\"x\">, right=#<struct IdentifierNode name=\"y\">>, right=#<struct IdentifierNode name=\"z\">>, right=#<struct ConstantNode type=:INT, value=42>>, #<struct NotEqualNode left=#<struct LessThanNode left=#<struct AddNode left=#<struct MulNode left=#<struct Not expr=#<struct IdentifierNode name=\"x\">>, right=#<struct IdentifierNode name=\"y\">>, right=#<struct IdentifierNode name=\"z\">>, right=#<struct IdentifierNode name=\"x\">>, right=#<struct LessThanNode left=#<struct ConstantNode type=:INT, value=42>, right=#<struct AddNode left=#<struct IdentifierNode name=\"x\">, right=#<struct MulNode left=#<struct IdentifierNode name=\"y\">, right=#<struct Not expr=#<struct IdentifierNode name=\"x\">>>>>>]>>]>"

    end
    it "parser/p05.c" do
        expect(parse("parser/p05.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct ArrayDeclarationNode type=:INT, name=\"c\", num_elements=10>, #<struct ArrayDeclarationNode type=:CHAR, name=\"d\", num_elements=10>, #<struct FunctionDeclarationNode type=:VOID, name=\"f\", formals=[#<struct ArrayDeclarationNode type=:INT, name=\"h\", num_elements=nil>, #<struct ArrayDeclarationNode type=:CHAR, name=\"i\", num_elements=nil>], body=#<struct FunctionBodyNode declarations=[], statments=[]>>, #<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[], statments=[]>>]>"

    end
    it "parser/p06.c" do
        expect(parse("parser/p06.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:VOID, name=\"f\", formals=[], body=#<struct FunctionBodyNode declarations=[], statments=[#<struct ReturnNode expr=:VOID>]>>, #<struct FunctionDeclarationNode type=:INT, name=\"g\", formals=[], body=#<struct FunctionBodyNode declarations=[], statments=[#<struct ReturnNode expr=#<struct ConstantNode type=:INT, value=42>>]>>, #<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[], statments=[#<struct CallNode name=\"f\", args=[]>, #<struct CallNode name=\"g\", args=[]>]>>]>"
    end
    it "parser/p07.c" do
        expect(parse("parser/p07.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[#<struct VariableDeclarationNode type=:INT, name=\"x\">, #<struct VariableDeclarationNode type=:INT, name=\"y\">], statments=[#<struct IfNode condition=#<struct IdentifierNode name=\"x\">, then_block=[#<struct WhileNode condition=#<struct IdentifierNode name=\"y\">, body=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=42>>]>], else_block=nil>, #<struct WhileNode condition=#<struct IdentifierNode name=\"x\">, body=[#<struct IfNode condition=#<struct IdentifierNode name=\"y\">, then_block=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=42>>], else_block=nil>]>]>>]>"

    end
    it "parser/p08.c" do
        expect(parse("parser/p08.c").inspect).to eq "#<struct ProgramNode nodes=[#<struct FunctionDeclarationNode type=:INT, name=\"main\", formals=[], body=#<struct FunctionBodyNode declarations=[#<struct VariableDeclarationNode type=:INT, name=\"x\">, #<struct VariableDeclarationNode type=:INT, name=\"y\">], statments=[#<struct IfNode condition=#<struct IdentifierNode name=\"x\">, then_block=[#<struct IfNode condition=#<struct IdentifierNode name=\"y\">, then_block=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=4711>>], else_block=[#<struct AssignNode left=#<struct IdentifierNode name=\"x\">, right=#<struct ConstantNode type=:INT, value=42>>]>], else_block=nil>]>>]>"
    end
end
